# Generated by Django 2.2 on 2019-04-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0002_bets_goalsbets_markerbets_winbets'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bets',
            table='bets',
        ),
        migrations.AlterModelTable(
            name='goalsbets',
            table='goals_bets',
        ),
        migrations.AlterModelTable(
            name='markerbets',
            table='marker_bets',
        ),
        migrations.AlterModelTable(
            name='payoffs',
            table='payoffs',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
        migrations.AlterModelTable(
            name='winbets',
            table='win_bets',
        ),
    ]
