# Generated by Django 2.2 on 2019-04-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0003_auto_20190405_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
    ]
