# Generated by Django 2.2 on 2019-04-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0004_remove_userprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='id_match',
            field=models.IntegerField(default=0),
        ),
    ]
